### ISSUE TITLE
Review 기본 환경 설정 관리

### ISSUE THREAD

**Issue by JianBBB** [TEAM21-2NE1/ticketing#10]
## 개발 사항 설명
개발 시작 전 필요한 설정 파일들 관리 

## TO-DO
- [ ] application.yml 관리
- [ ] build.gradle에 의존성 추가 
- [ ] .gitignore 수정
- [ ] configuration 파일들 생성
