### ISSUE TITLE
결제 요청 페이지 주문 서비스로 리팩토링

### ISSUE THREAD

**Issue by dowonidaa** [TEAM21-2NE1/ticketing#130]
## 개발 사항 설명
- 결제요청페이지 결제서비스에서 주문서비스로 이동
- 결제 검증 완료후 주문 성공 로직 try 안으로 이동
- 주문 취소시 주문 서비스 레디스 좌석 상태 available로 변경 추가
## TO-DO
- [x] 결제 요청페이지 주문 서비스로 이동
- [x] try 안으로 이동
- [x] 레디스 좌석 상태 변경 추가
