### ISSUE TITLE
Review 평균 평점 구하기 리팩터링 

### ISSUE THREAD

**Issue by JianBBB** [TEAM21-2NE1/ticketing#134]
## 개발 사항 설명
1. Review CUD 과정에서 레디스에 실시간으로 평점 반영 -> 스케줄링으로 1시간 마다 반영하도록 리팩터링  

## TO-DO
- [ ] Spring Application Event 기능 제거 
- [ ] 스케줄링 추가 
- [ ] 평균 평점 가져오던 Lua Script 삭제 
- [ ] 평균 평점 세팅하던 Lua Script 리팩터링
