### ISSUE TITLE
Performance 예외 처리

### ISSUE THREAD

**Issue by dowonidaa** [TEAM21-2NE1/ticketing#16]
## 개발 사항 설명
Performance service 예외처리 및 요청 검증 처리

## TO-DO
- [x] custom exception 구현
- [x] exception handler 구현
- [x] request validation 구현
