### ISSUE TITLE
Performance 목록조회 리팩터링

### ISSUE THREAD

**Issue by dowonidaa** [TEAM21-2NE1/ticketing#42]
## 개발 사항 설명
- performance 목록 open date 기준으로 조회 수정  
- 검색 title, description 검색 기능 추가
## TO-DO
- [ ] page custom
- [ ] pagable custom
- [ ] querydsl 전용 repository 추가
- [ ] performance 목록 open date 기준으로 조회 수정  
- [ ] 검색 title, description 검색 기능 추가
