### ISSUE TITLE
Review Feign Client 초안 설계

### ISSUE THREAD

**Issue by JianBBB** [TEAM21-2NE1/ticketing#49]
## 개발 사항 설명
내부 통신을 위한 Feign Client 초안 설계 

## TO-DO
- [x] Performance 서버에서 performanceId에 대한 공연 정보 요청 구현
- [x] User 서버에 userId에 대한 nickname 데이터 요청 구현
- [ ] Order 서버에 예매 정보 요청 구현
