### ISSUE TITLE
User 회원가입 구현

### ISSUE THREAD

**Issue by soy9** [TEAM21-2NE1/ticketing#7]
## 개발 사항 설명
user-service에 User Entity를 생성하고, 
회원가입 api 개발 및 테스트를 통해 전반적인 설정 관련 테스트를 함께 진행할 예정입니다.

## TO-DO
- [x] 패키지 구조 생성
- [x] DB(postgres) 설정(의존성, 설정 정보)
- [x] User Entity 생성
- [x] 회원가입 API 개발
