### ISSUE TITLE
Performance Seat 목록조회 redis 적용, 좌석선택 기능 구현

### ISSUE THREAD

**Issue by dowonidaa** [TEAM21-2NE1/ticketing#74]
## 개발 사항 설명
- 목록 조회 redis 적용
- 좌석 선택 기능 구현
## TO-DO
- [x] 목록조회 redis 적용
- [x] 좌석 선택 기능 구현
- [x] 좌석 예매 확정, 취소 redis 데이터 동기화
- [x] 기타 검증사항 추가
