### ISSUE TITLE
Performance 좌석 조회 bug fix

### ISSUE THREAD

**Issue by dowonidaa** [TEAM21-2NE1/ticketing#78]
## 문제 상황 설명
- 공연 performanceTime 이후에 조회시 좌석 조회 error
### TO-DO
- [x] 공연 조회시에 사용하는 좌석 조회 메서드 수정
- [x] 주문시에 사용하는 좌석조회 메서드 추가
- [x] 공연 상세조회시 openDate 이전 공연 예외처리
